# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/andydydy91-helios/WarTycoonLauncher/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/andydydy91-helios/WarTycoonLauncher/"
supportLink = "https://github.com/andydydy91-helios/WarTycoonLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue Sur Helios Launcher"
welcomeDescription = "Notre Mission, Offrir aux joueurs une expérience immersive et accessible dans l’univers de Helios. Grâce à Helios, nous nous engageons à fournir un launcher performant, sécurisé, et facile à utiliser, pour que chaque aventure commence sans obstacle. Nous mettons tout en œuvre pour que votre voyage soit fluide, enrichissant, et inoubliable."
welcomeDescCTA = "Vous n’êtes qu’à quelques clics de Helios."
