[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités..."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélection du compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter ou gérer vos comptes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran"
autoConnectTitle = "Connexion automatique au serveur au démarrage"
launchDetachedTitle = "Lancer le jeu indépendamment du launcher"
launchDetachedDesc = "Sinon, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer de serveur"
requiredMods = "Mods obligatoires"
optionalMods = "Mods optionnels"
dropinMods = "Mods ajoutés manuellement"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaders"
shaderpackDesc = "Activez/désactivez les shaders. Fonctionne mieux sur des machines puissantes."
selectShaderpack = "Sélectionner un shaderpack"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Configurer Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "3 Go recommandés minimum. Même valeur min/max peut réduire les lags."
memoryTotalTitle = "Totale"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner un exécutable Java"
javaExecSelButtonText = "Choisir le fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à passer à la JVM au lancement. Ne pas inclure -Xms ou -Xmx."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher."
allowPrereleaseTitle = "Autoriser les versions préliminaires"
allowPrereleaseDesc = "Ces versions contiennent des nouveautés instables. Toujours actif si vous utilisez une version pré-release."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner un dossier"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = """
Tous les fichiers du jeu et Java local seront stockés ici.<br>Les captures d’écran et les mondes sont enregistrés dans le dossier d'instance correspondant.
"""
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Informations et notes de version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note disponible"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Consultez la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur au lancement"
failureText = "Consultez la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos système..."
noCompatibleJava = "Aucune installation Java compatible trouvée"
installJavaMessage = "Java {major} 64 bits est requis pour lancer Minecraft. Souhaitez-vous que nous l'installions ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus d'informations."
javaRequired = """
Java est requis<br>pour lancer le jeu
"""
javaRequiredMessage = """
Une installation Java {major} 64 bits valide est requise.<br><br>Voir notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide d'installation Java</a>.
"""
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la détection d'une distribution OpenJDK."
javaDownloadCorruptedError = "Le fichier JDK téléchargé est corrompu (hash invalide)."
extractingJava = "Extraction de Java..."
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur au lancement"
seeConsoleForDetails = "Voir la console pour plus d’informations."
validatingFileIntegrity = "Vérification de l'intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur de vérification"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur de téléchargement"
preparingToLaunch = "Préparation au lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = """
Échec du téléchargement du fichier principal LaunchWrapper. Essayez de désactiver temporairement votre antivirus, puis relancez le jeu.
"""
doneEnjoyServer = "Terminé. Bon jeu !"
checkConsoleForDetails = "Consultez la console pour plus d’informations."

[js.landing.news]
checking = "Vérification des actualités..."

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route vers Westeros !"
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur s'est produite"
errorMessage = "Échec de l'authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur s'est produite"
errorMessage = "Échec de la déconnexion Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Dernier compte actif"
lastAccountWarningMessage = "Vous devez rester connecté à au moins un compte pour utiliser le launcher.<br><br>Vous devrez vous reconnecter après."
confirmButton = "Je confirme"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé, puis réessayez."
failedToggleTitle = "Échec du changement<br>d’état d’un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requiert Java {major} 64 bits."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement..."
downloadButton = """
Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et exécutez le fichier dmg pour mettre à jour.</span>
"""
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Recherche de mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible de vous connecter. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Impossible de charger l’index"
fatalErrorMessage = """
Impossible de se connecter aux serveurs pour obtenir l’index de distribution. Aucun fichier local disponible. Vérifiez votre connexion Internet.
"""
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = """
Impossible de rafraîchir la session de <strong>{account}</strong>. Sélectionnez un autre compte ou reconnectez-vous.
"""
failedMessageSelectAnotherAccount = "Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = """
Votre compte Microsoft ne possède pas encore de profil Minecraft. Configurez-le sur <a href="https://minecraft.net/">Minecraft.net</a>.
"""
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Aucun compte Xbox n’est lié à ce compte Microsoft."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d’un pays où Xbox Live est indisponible."
under18Title = "Erreur de connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue"
unknownDesc = "Une erreur inconnue est survenue. Consultez la console."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Merci de signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Point d’authentification introuvable. Merci de le signaler."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Utilisez votre email comme identifiant."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "Email ou mot de passe incorrect."
tooManyAttemptsTitle = "Erreur :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives. Réessayez plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Token invalide"
invalidTokenDesc = "Le token fourni est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Profil déjà assigné"
tokenHasProfileDesc = "Le profil est déjà lié à ce token."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d'utilisateur ou mot de passe manquant (ou trop court)."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non pris en charge"
unsupportedMediaTypeDesc = "Type de média non supporté. Merci de signaler."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Connectez-vous avec un compte Microsoft."
unreachableTitle = "Erreur de connexion :<br>Serveur injoignable"
unreachableDesc = "Impossible de contacter les serveurs d’authentification."
gameNotPurchasedTitle = "Erreur :<br>Jeu non acheté"
gameNotPurchasedDesc = """
Ce compte n’a pas acheté Minecraft. Achetez-le sur <a href="https://minecraft.net/">Minecraft.net</a>.
"""
unknownErrorTitle = "Erreur inconnue"
unknownErrorDesc = "Une erreur s’est produite. Consultez la console."
